services:

  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres-master
    restart: always
    shm_size: 128mb
    ports:
    - 5432:5432
    environment:
    - POSTGRESQL_REPLICATION_MODE=master
    - POSTGRESQL_REPLICATION_USER=repl_user
    - POSTGRESQL_REPLICATION_PASSWORD=repl_password
    - POSTGRESQL_USERNAME=postgres
    - POSTGRESQL_PASSWORD=123456
    - POSTGRESQL_DATABASE=book
    - ALLOW_EMPTY_PASSWORD=yes
    networks:
    - os-net
    volumes:
    - 'postgresql_master_data:/bitnami/postgresql'
    - ./scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: pg_isready -U postgres -d book
      interval: 10s
      timeout: 3s
      retries: 3

  postgres-slave:
    image: bitnami/postgresql:latest
    container_name: postgres-slave
    restart: always
    shm_size: 128mb
    ports:
    - 5433:5432
    environment:
    - POSTGRESQL_REPLICATION_MODE=slave
    - POSTGRESQL_REPLICATION_USER=repl_user
    - POSTGRESQL_REPLICATION_PASSWORD=repl_password
    - POSTGRESQL_MASTER_HOST=postgres
    - POSTGRESQL_PASSWORD=123456
    - POSTGRESQL_MASTER_PORT_NUMBER=5432
    - ALLOW_EMPTY_PASSWORD=yes
    - POSTGRESQL_EXTENSIONS=pg_trgm
    networks:
    - os-net
    volumes:
    - ./scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: pg_isready -U postgres -d book
      interval: 10s
      timeout: 3s
      retries: 3
    depends_on:
      postgres:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    restart: always
    ports:
    - 5672:5672
    - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: kalo
      RABBITMQ_DEFAULT_PASS: kalo
    volumes:
    - rabbitmq-lib:/var/lib/rabbitmq/
    - rabbitmq-log:/var/log/rabbitmq
    networks:
    - os-net
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 3

  application:
    container_name: application-test
    build:
      context: .
      dockerfile: ./Dockerfile
      target: test
    image: book-service-test:${TESTE_VERSION:-latest}
    restart: always
    volumes:
    - .:/code
    environment:
    - SYSTEM_ENVIRONMENT=local
    - SYSTEM_HOST=0.0.0.0
    - SYSTEM_PORT=9000
    - DATABASE_HOST=postgres
    - DATABASE_PORT=5432
    - DATABASE_SLAVE_HOST=postgres-slave
    - DATABASE_SLAVE_PORT=5432
    - DATABASE_USER=postgres
    - DATABASE_PASSWORD=123456
    - DATABASE_NAME=book
    - LOGSTASH_HOST=logstash
    - LOGSTASH_PORT=5000
    - PRODUCER_LOCALHOST=rabbitmq
    - PRODUCER_USER=kalo
    - PRODUCER_PASSWORD=kalo
    - CONSUMER_LOCALHOST=rabbitmq
    - CONSUMER_USER=kalo
    - CONSUMER_PASSWORD=kalo
    - SYSTEM_EXECUTOR=api
    networks:
    - os-net
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

volumes:
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local
  postgresql_master_data:
    driver: local

networks:
  os-net:
    driver: bridge
